### ISSUE TITLE
If;else translation

### ISSUE THREAD

**Issue by basondole** [Kalebu/pyswahili#1]
If...else, should be ikiwa...badala

**Comment by basondole** [comment]
For Else use badala or mbadala

**Comment by Kalebu** [comment]
I have received your suggestion, will pass some voting to select the
convinient keywords

Thanks for contributing

**Comment by basondole** [comment]
Hi that’d be great, but I don’t think translation is a voting matter, sorry; 🥶translation is about meaning and relation of the words.

**Comment by basondole** [comment]
We are not choosing a method or workflow, we are translating 😉 Strictly speaking from language perspective there.

**Comment by ibnsultan** [comment]
@basondole semantical rules do not matter in programming, the main goal is not just to have a language that uses swahili lexical terms to program, but a language that uses swahili lexical terms to ease the grasp of programming concept.
